### ISSUE TITLE
Menu animation does not seem to kick in - the popup just disappears

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/dropdown_search#681]
Hi @salim-lachdhaf 
Long time no see!
Thanks for this huge update

**Describe the bug**
I turned on "Run animations 5 times slower" in devtools
Check the video
- dropdown arrow icon swaps immediately to `closed` state(it would be nice to sync animation)
- popup window just disappears without animation

https://github.com/user-attachments/assets/41a912a5-3f53-46a4-b4cb-7b747c1891c9

**To Reproduce**
1. run example app
2. enable `run animations 5 times slower` in dev tools
3. open/close the popup

**Expected behavior**
Popup animates nicely in sync with dropdown icon

**Comment by salim-lachdhaf** [comment]
You know, free time is rare nowadays.

I hope you like the new features! 😉

Currently, neither the `menu` nor the `dropdownButton` supports animation. 

I can easily add animation to the `menu`, but I’m still not sure how to handle it for the `dropdownButton`. Any help would be appreciated!

**Comment by salim-lachdhaf** [comment]
Features added (and a huge other), will be released once flutter team releases a fix for this issue https://github.com/flutter/flutter/issues/155901

Stay tuned  ;)
