### ISSUE TITLE
Add a way to refresh data especially when error.

### ISSUE THREAD

**Issue by Trung15010802** [salim-lachdhaf/dropdown_search#682]
**Is your feature request related to a problem? Please describe.**
Add a feature to refresh data when error.

**Describe the solution you'd like**
Using search box isn't a good way

**Comment by salim-lachdhaf** [comment]
What do you suggest ?

**Comment by Trung15010802** [comment]
> What do you suggest ?

I want some function to trigger `items ` function again in errorBuilder

**Comment by salim-lachdhaf** [comment]
Feature added in v7.0.0-pre.

for inifiniteScroll use `infiniteScrollDropDownKey.currentState?.getPopupState?.loadMoreItems(searchEntry, loadProps.skip);` like here https://github.com/salim-lachdhaf/dropdown_search/blob/7781323781ad6938e83997d67239e8dd5a33bbbb/example/lib/material/dialogs.dart#L384

For general error use :  `mDropDownKey.currentState?.getPopupState?.reloadItems(searchEntry);`
