### ISSUE TITLE
Another exception was thrown: setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by GaioCatullo** [salim-lachdhaf/dropdown_search#692]
in My Widget i pass a function
final Function(FleetDTO)? onChanged;

I return function to father
      onChanged: (value) {       
        widget.onChanged!(value!);
      },
      
   in father;
           setState(() {
         selectedFleet = value;

        widget.pSelect.value =
            (value.fpkdx > 0); // != null || (widget.shift.value!.fpkdx! > 0));
        widget.shift.value!.fpkdx = value.fpkdx;
        widget.shift.value!.selectiv = value.fpsel;
        widget.shift.value!.fpklass = value.idklasse;
        widget.shift.value!.idKategorie = value.idkategorie;
        widget.shift.value!.tetra = value.tetra;
        widget.driverLevel.value = value.idFahrerstufe;

        print(value.aed || value.aedManuell);
        if (value.aed || value.aedManuell) {
          widget.shift.value!.aed = true;
        } else {
          widget.shift.value!.aed = false;
        }
        });
        i get this :
        
        exception was thrown: setState() or markNeedsBuild() called during build.

**Comment by salim-lachdhaf** [comment]
But where the DropdownSearch ? Could you past a reproducible simple example to issue ?

**Comment by salim-lachdhaf** [comment]
No updates.
