### ISSUE TITLE
Multiselect and multilevel at the same time.

### ISSUE THREAD

**Issue by garyloud** [salim-lachdhaf/dropdown_search#697]
I'm trying to get a multilevel along with a multiselect working.  Everything works but I get a checkbox on the level one items that I don't want.  I've looked at the code but there doesn't seem to be an option to not generate the checkbox on the level one items.  Is this something I've missed or does this option not exist?

I have attached a screenshot of the issue.

Thanks,
Gary
<img width="500" alt="Screenshot 2024-10-11 at 12 22 56" src="https://github.com/user-attachments/assets/f2a4f875-b0c1-4f1d-9c76-6133a9f9a7c5">

**Comment by salim-lachdhaf** [comment]
Did you tried to use `checkBoxBuilder` property of `popupProps` ?

**Comment by garyloud** [comment]
I tried setting it to null but that didn't work and just now after receiving your email I tried it returning an empty Container() and it works just like I wanted it to.  Thank you for responding so quickly.

**Comment by salim-lachdhaf** [comment]
You should not put it to null because in this case will take the default widget.

Use `SizedBox.shrink()` .

Please don't hesitate to star the repo and the lib if it's useful for you.
