### ISSUE TITLE
Laggy/delayed animations

### ISSUE THREAD

**Issue by fikretsengul** [salim-lachdhaf/dropdown_search#699]
I use the latest flutter and dropdown_search version. The package runs slow like there is a delay on animations which feels bad. Here is the comparison video with flutter's own dropdown:

https://github.com/user-attachments/assets/b4d0ccf5-dc8d-470b-af25-c53c06721839

**Comment by salim-lachdhaf** [comment]
By default there is a delay of 300 milliseconds.
You can change it by setting  `duration` to `Duration.zero` in `popUpAnimationStyle` properties of `menuProp`.

**Comment by fikretsengul** [comment]
Of course, the configuration and customizability you offer is unmatched. Not to mention the speed with which you help. Thank you for this wonderful library.

By the way, 'decoratorProps' in reactive_dropdown_search library is incompatible with Mode.custom. It needs to be changed like this:

decoratorProps: mode == Mode.custom
    ? null
    : DropDownDecoratorProps(

**Comment by fikretsengul** [comment]
Making the duration 0 solves the problem, but there is a general problem with the animation. I couldn't manage to fade in and fade out slowly, the animation just doesn't work. The menu opens immediately and disappears late. I don't think the setting below works:

popUpAnimationStyle: AnimationStyle(
  curve: Curves.ease,
  duration: const Duration(seconds: 1),
  reverseCurve: Curves.ease,
  reverseDuration: const Duration(seconds: 1),
),

**Comment by salim-lachdhaf** [comment]
`reactive_dropdown_search` library is not mine.
`DropdownSearch` is already reactive and no need to state management to update it's state and you can manage it programmatically using `GlobalKey.`

For the animation, in the current version there is no real animation feature. But this is added as a feature in the next version as mentioned [here](https://github.com/salim-lachdhaf/dropdown_search/issues/681)

**Comment by fikretsengul** [comment]
Actually its just a wrapper for reactive_forms support. Thanks for the information.
