### ISSUE TITLE
Can't make scrollbar always shown

### ISSUE THREAD

**Issue by youssefasultan** [salim-lachdhaf/dropdown_search#701]
**Describe the bug**
I tried to make the scrollbar always show, I've tried all the options, and nothing happens whether changing Tumb or track color.

**Smartphone (please complete the following information):**
 - Device: Samung s20 fe

**Comment by salim-lachdhaf** [comment]
Have you a simple reproducible sample ?
Did you tried to show the scrollbar without using the package ?

**Comment by youssefasultan** [comment]
> Have you a simple reproducible sample ? Did you tried to show the scrollbar without using the package ?

how can I show it without using the package?

**Comment by salim-lachdhaf** [comment]
> > Have you a simple reproducible sample ? Did you tried to show the scrollbar without using the package ?
> 
> how can I show it without using the package?

i meant use an example with  listView for example and force the scrollbar to be shown.


Otherwise please past an reproducible sample to analyse the issue

**Comment by youssefasultan** [comment]
`DropdownSearch<String>(
                  key: plantDropDownKey,
                  autoValidateMode: AutovalidateMode.onUnfocus,
                  items: (filter, infiniteScrollProps) =>
                      context.appDataProvider.getPlant!,
                  selectedItem: context.appDataProvider.getSelectedPlant,
                  suffixProps: DropdownSuffixProps(
    dropdownButtonProps: DropdownButtonProps(
      iconClosed: Icon(Icons.keyboard_arrow_down),
      iconOpened: Icon(Icons.keyboard_arrow_up),
    ),
  ),
                  decoratorProps: DropDownDecoratorProps(
        textAlign: TextAlign.start,
        decoration: InputDecoration(
          contentPadding:
              const EdgeInsets.symmetric(vertical: 10, horizontal: 10),
          filled: true,
          fillColor: Colors.white,
          disabledBorder: OutlineInputBorder(
            borderSide: const BorderSide(color: SColors.darkGrey),
            borderRadius: BorderRadius.circular(5),
          ),
          border: OutlineInputBorder(
            borderSide: const BorderSide(color: Colors.transparent),
            borderRadius: BorderRadius.circular(5),
          ),
          focusedBorder: OutlineInputBorder(
            borderSide: const BorderSide(color: SColors.secondaryColor),
            borderRadius: BorderRadius.circular(5),
          ),
          enabledBorder: OutlineInputBorder(
            borderSide: const BorderSide(color: SColors.darkGrey),
            borderRadius: BorderRadius.circular(5),
          ),
          hintText: 'Please select $label',
          hintStyle: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 12,
            color: SColors.darkGrey,
          ),
        ),
      ),
                  popupProps: PopupProps<String>.menu(
    itemBuilder: (context, item, isDisabled, isSelected) {
      return Padding(
        padding: const EdgeInsets.symmetric(vertical: 12.0, horizontal: 2),
        child: Text(
          item,
          style: context.textTheme.bodySmall,
        ),
      );
    },
    constraints: const BoxConstraints(maxHeight: 120),
    scrollbarProps: const ScrollbarProps(
      thumbVisibility: true, // nothing changes
      trackVisibility: true,// 
    ),
    menuProps: const MenuProps(
      margin: EdgeInsets.only(top: 1),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.all(Radius.circular(12)),
      ),
    ),
  ),
                  
                  validator: (value) =>
                      SValidator.validateEmptyText('Plant', value),
                  onChanged: (value) {
                    context.appDataProvider.selectedPlant = value;

                    context.appDataProvider.setDropdownList(
                      fieldName: 'storageLocation',
                    );
                  },
                ),`

**Comment by youssefasultan** [comment]
`DropdownSearch(
key: plantDropDownKey,
autoValidateMode: AutovalidateMode.onUnfocus,
items: (filter, infiniteScrollProps) =>
context.appDataProvider.getPlant!,
selectedItem: context.appDataProvider.getSelectedPlant,
suffixProps: DropdownSuffixProps(
dropdownButtonProps: DropdownButtonProps(
iconClosed: Icon(Icons.keyboard_arrow_down),
iconOpened: Icon(Icons.keyboard_arrow_up),
),
),
decoratorProps: DropDownDecoratorProps(
textAlign: TextAlign.start,
decoration: InputDecoration(
contentPadding:
const EdgeInsets.symmetric(vertical: 10, horizontal: 10),
filled: true,
fillColor: Colors.white,
disabledBorder: OutlineInputBorder(
borderSide: const BorderSide(color: SColors.darkGrey),
borderRadius: BorderRadius.circular(5),
),
border: OutlineInputBorder(
borderSide: const BorderSide(color: Colors.transparent),
borderRadius: BorderRadius.circular(5),
),
focusedBorder: OutlineInputBorder(
borderSide: const BorderSide(color: SColors.secondaryColor),
borderRadius: BorderRadius.circular(5),
),
enabledBorder: OutlineInputBorder(
borderSide: const BorderSide(color: SColors.darkGrey),
borderRadius: BorderRadius.circular(5),
),
hintText: 'Please select $label',
hintStyle: const TextStyle(
fontWeight: FontWeight.bold,
fontSize: 12,
color: SColors.darkGrey,
),
),
),
popupProps: PopupProps.menu(
itemBuilder: (context, item, isDisabled, isSelected) {
return Padding(
padding: const EdgeInsets.symmetric(vertical: 12.0, horizontal: 2),
child: Text(
item,
style: context.textTheme.bodySmall,
),
);
},
constraints: const BoxConstraints(maxHeight: 120),
scrollbarProps: const ScrollbarProps(
thumbVisibility: true, // nothing changes
trackVisibility: true,//
),
menuProps: const MenuProps(
margin: EdgeInsets.only(top: 1),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.all(Radius.circular(12)),
),
),
),

              validator: (value) =>
                  SValidator.validateEmptyText('Plant', value),
              onChanged: (value) {
                context.appDataProvider.selectedPlant = value;

                context.appDataProvider.setDropdownList(
                  fieldName: 'storageLocation',
                );
              },
            ),`
`

**Comment by youssefasultan** [comment]
`PopupProps<String>.menu(
    itemBuilder: (context, item, isDisabled, isSelected) {
      return Padding(
        padding: const EdgeInsets.symmetric(vertical: 12.0, horizontal: 2),
        child: Text(
          item,
          style: context.textTheme.bodySmall,
        ),
      );
    },
    constraints: const BoxConstraints(maxHeight: 120),
    scrollbarProps: const ScrollbarProps(
      thumbVisibility: true, // doesn't change anything
      trackVisibility: true, // same here
    ),
    menuProps: const MenuProps(
      margin: EdgeInsets.only(top: 1),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.all(Radius.circular(12)),
      ),
    ),
  ),`

**Comment by salim-lachdhaf** [comment]
tested on chrome. it works fine.


```
DropdownSearch<String>(
                        items: (filter, loadProps) => ["1", "2", "3", "4", "10", "200", "3000", "40000"],
                        selectedItem: "2",
                        suffixProps: DropdownSuffixProps(clearButtonProps: ClearButtonProps(isVisible: true)),
                        popupProps: PopupProps<String>.menu(
                          itemBuilder: (context, item, isDisabled, isSelected) {
                            return Padding(
                              padding: const EdgeInsets.symmetric(vertical: 12.0, horizontal: 2),
                              child: Text(item),
                            );
                          },
                          constraints: const BoxConstraints(maxHeight: 120),
                          scrollbarProps: const ScrollbarProps(
                            thumbVisibility: true, // doesn't change anything
                            trackVisibility: true, // same here
                          ),
                          menuProps: const MenuProps(
                            margin: EdgeInsets.only(top: 1),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.all(Radius.circular(12)),
                            ),
                          ),
                        ),
                      )
```
![image](https://github.com/user-attachments/assets/3afccd6e-2256-40ce-ae78-c0175d278e6d)

please check your theme settings.
