### ISSUE TITLE
How to call the validator on a button click ?

### ISSUE THREAD

**Issue by PKReejesh** [salim-lachdhaf/dropdown_search#707]
I wish to call the validator on a button click and highlight the error, is that possible with this widget ?

I have seen the autoValidateMode mode, but is there a manual way to trigger the validate method and show the error ?

**Comment by salim-lachdhaf** [comment]
Yes you can, use `AutovalidateMode.disabled` and validate your form in demand by calling `formKey.validate()`
Where `formKey` is `GlobalKey` to be assigned to your `Form` .

don't forget to implement `validator` for your `DropdownSearch`

Take a look [here ](https://docs.flutter.dev/cookbook/forms/validation).

Please don't hesitate to like the repo and the lib if it's helpful for you.
