### ISSUE TITLE
How to prevent click outside of Multi select bottom sheet ?

### ISSUE THREAD

**Issue by PKReejesh** [salim-lachdhaf/dropdown_search#708]
Using
 PopupPropsMultiSelection.bottomSheet

But it allows click outside of the bottom sheet, allowing background items to be clicked. Is there any way to prevent or blur out the background items

Im using this exampld https://github.com/salim-lachdhaf/dropdown_search/blob/fa960038cf08df53da4513b4f96c1eb4b9a971cf/example/lib/bottom_sheets.dart#L112

**Comment by salim-lachdhaf** [comment]
it's a normal behavior of a bottomSheet and it's not related to package.

in your case use `PopupPropsMultiSelection.modalBottomSheet` which block access to background items.

Please don't hesitate to like the repo and the lib if it's useful for you.
