### ISSUE TITLE
Add onTapOutside functionality to unfocus or close DropdownSearch

### ISSUE THREAD

**Issue by soufianebenyaala** [salim-lachdhaf/dropdown_search#711]
**Is your feature request related to a problem? Please describe.**
When using a DropdownSearch widget, it's frustrating that if a user taps outside of the dropdown, it doesn't automatically close or unfocus. This can lead to an unintentional open dropdown if the user tries to interact with other parts of the screen.

**Describe the solution you'd like**
I would like to add a feature where, upon tapping outside of the DropdownSearch widget, it will automatically unfocus or close. This will improve the user experience by ensuring that the dropdown only remains open when needed.

**Describe alternatives you've considered**
An alternative could be to implement a manual close button inside the dropdown, but that requires additional user interaction. Tapping outside to close feels more intuitive.

**Additional context**
This feature could be particularly useful when the dropdown contains a large list of items, and the user may want to quickly close it to focus on other UI elements. Additionally, providing a way to close the dropdown by tapping outside would help avoid cluttering the screen with extra UI elements.

**Comment by salim-lachdhaf** [comment]
This behavior exists already, except Bottomsheet mode.

**Comment by salim-lachdhaf** [comment]
no updates.
