### ISSUE TITLE
Call refresh of items programatically when data in database/online

### ISSUE THREAD

**Issue by iksivee** [salim-lachdhaf/dropdown_search#713]
**Is your feature request related to a problem? Please describe.**
I use limitations for items that are based on other fields of form. I am using ChoiceChip inside containerBuilder above search bar. If I unselect the chip, I need to refresh items because there will be different set of items when limiting or not limiting by other fields. 

**Describe the solution you'd like**
I would like to call: dropDownKey.currentState?.refreshItems();

**Describe alternatives you've considered**
I have done the only I found working but it has side effects like calling refresh twice and blinking of hint text of TextEditingControl for search bar.

```
void _tecSimulateChange(TextEditingController tec) {
    var txt = tec.text;

    setState(() {
      //tec = new TextEditingController(text: tec.text); // not working
      tec.text = tec.text + ' ';
    });

    //WidgetsBinding.instance.addPostFrameCallback((_) { }); // not working
    //Future.delayed(Duration.zero, () { // not working

    Future.delayed(Duration(milliseconds: 300), () {
      setState(() {
        tec.text = txt;
      });
    });

    //_dropDownKey.currentState?.updatePopupState(); // does not refresh items
  }
```

**Additional context**
![image](https://github.com/user-attachments/assets/578997f6-e57a-475c-80af-ad64b9006b51)

**Comment by salim-lachdhaf** [comment]
feature added in v7.0.0-pre. just call `myDropDownKey.currentState?.getPopupState?.reloadItems(searchEntry);`
