### ISSUE TITLE
Use of DropDownSearch without visible drop down field

### ISSUE THREAD

**Issue by iksivee** [salim-lachdhaf/dropdown_search#714]
**Is your feature request related to a problem? Please describe.**
We need sometimes to display only dialog with dropDownSearch items because user needs to decide which item to choose. But we do not have any visible field of drop down. 

**Describe the solution you'd like**
Option to use only dialog/modal window to choose items from DropDownSearch.

**Describe alternatives you've considered**
Currently we solved it by using fake dialog with single DropDownSearch field and immediately after open of fake dialog we show dialog of DropDownSearch. Finally we close both dialogs. It is not convenient approach and had issues with landscape mode.

```
   return showDialog<MyObject?>(
        context: context,
        barrierDismissible: true,
        builder: (context) {
          WidgetsBinding.instance.addPostFrameCallback(
              (_) => _openDropDownProgKey.currentState?.openDropDownSearch());

          return AlertDialog(
            key: UniqueKey(),
            title: Container(
              child: Stack(
                children: <Widget>[
                  DropdownSearch<MyObject>(
                    key: _openDropDownProgKey,
....
```

**Comment by salim-lachdhaf** [comment]
Do you want to show only items (the poup) without need to click on the dropdownForm ?

**Comment by iksivee** [comment]
Yes, without a visible field with selected items, label etc.

**Comment by salim-lachdhaf** [comment]
In this case, did you tried to use this class `DropdownSearchPopup`

**Comment by iksivee** [comment]
Hello, 
sorry for delay, I did not have time to try that. 
It works like a charm, just used DropdownSearchPopup as a widget. 
Thank you very much! We will sponsor this package soon 👍
