### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe when dropdown is inside a navigator

### ISSUE THREAD

**Issue by GP4cK** [salim-lachdhaf/dropdown_search#717]
**Describe the bug**
When the parent navigator of the dropdown gets disposed, the following exception is thrown:

**To Reproduce**
1. Clone https://github.com/GP4cK/dropdown_closing_issue
2. Click on the dropdown to open the menu
3. While the menu is still opened, click on "click me" at the top

**Expected behavior**
There should be no error

**Screenshots**

https://github.com/user-attachments/assets/f83c757b-89cd-4044-a889-c630278e94fe

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 15.1.1

**Comment by GP4cK** [comment]
I think if in `void closePopup() => Navigator.pop(context);` we were checking if the context was still mounted, that would solve the issue.
I'd be happy to do a PR if you think this is the right way to fix it.

**Comment by salim-lachdhaf** [comment]
thank you for reporting that.

and yes, testing on context's `mounted` solves the problem even it's weired, because `closePopup()` is called before `dropdownSearch` dispose !

in all cases, this is will be fixed in the v7.0.0-pre which will be released today.
