### ISSUE TITLE
_getBaseTextStyle does not overrides `color` to `Theme.of(context).disabledColor`

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/dropdown_search#720]
**Describe the bug**
`_getBaseTextStyle` does not overrides `color` to `Theme.of(context).disabledColor`

**To Reproduce**
1. Create dropdown
2. Pass `baseStyle` with `color: Colors.red` to `decoratorProps`
3. make dropdown disabled
4. disabled color not applied cause we are using `TextStyle(color).merge(baseSytle)` which overrides the color from `baseStyle`

**Expected behavior**
Disabled color should have more priority it makes sense to do baseStyle.copyWith(color: Theme.of(context).disabledColor)

**Comment by salim-lachdhaf** [comment]
Thnx for the PR, i will check that. I remember used the same behavior as textfield.

**Comment by salim-lachdhaf** [comment]
i confirm that the current behavior is working as expacted (same as TextField behavior). it's a merge not a copy of color.


![image](https://github.com/user-attachments/assets/695d25b5-8f4f-4b94-b255-dd31b846d8de)

```
Row(
            children: [
              Expanded(
                child: TextField(
                  enabled: false,
                  controller: TextEditingController(text: 'Hello !'),
                  style: TextStyle(color: Colors.red),
                ),
              ),
              Padding(padding: EdgeInsets.all(16)),
              Expanded(
                child: DropdownSearch(
                  decoratorProps: DropDownDecoratorProps(baseStyle: TextStyle(color: Colors.red)),
                  selectedItem: 'Hello !',
                  enabled: false,
                ),
              ),
            ],
          )
```

and this without overinding color.
![image](https://github.com/user-attachments/assets/b233ebb9-5476-499c-b3a7-f1dcdd34537c)
