### ISSUE TITLE
Infinite list (lazy loading) is not explain properly how to use this ?

### ISSUE THREAD

**Issue by rupendraa** [salim-lachdhaf/dropdown_search#721]
Infinite list (lazy loading) is not explain properly how to use this ?

need a full example of source code with working of Infinite list (lazy loading)

**Comment by salim-lachdhaf** [comment]
as mentionned by @vasilich6107 you can check that example.

other wise, to use infinite scroll all you have to do is define `infiniteScrollProps` like this for example 
`infiniteScrollProps: InfiniteScrollProps(loadProps: LoadProps(skip: 0, take: 10)),`

and of course on your items you have to pass the take and the offset to your API like this for example:
`items: (f, ic) => _getData(f, ic),`

i will add an example in Readme file.
