### ISSUE TITLE
`dropdownButtonPressed` is always not `null` so `dropdownButtonProps.disabledColor` never works

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/dropdown_search#722]
**Describe the bug**
`disabledColor` never applied
see https://github.com/salim-lachdhaf/dropdown_search/blob/fa960038cf08df53da4513b4f96c1eb4b9a971cf/lib/dropdown_search.dart#L518C24-L518C45

**To Reproduce**
1. Create dropdown
2. mark disabled
3. check disabled icon button color

**Expected behavior**
`disabledColor` applied to the button

**Comment by salim-lachdhaf** [comment]
I confirm that this is working as expected. suffix buttons are disabled (color and click).

_Tested in the current branch of the v7.0.0-pre which will be released today._


![image](https://github.com/user-attachments/assets/0bba9f87-8bda-4ee4-beaa-821274f73dce)

```
Row(
            children: [
              Expanded(
                child: DropdownSearch(
                  selectedItem: 'Enabled !',
                  suffixProps: DropdownSuffixProps(
                    clearButtonProps: ClearButtonProps(isVisible: true),
                  ),
                ),
              ),
              Padding(padding: EdgeInsets.all(16)),
              Expanded(
                child: DropdownSearch(
                  selectedItem: 'Disabled !',
                  enabled: false,
                  suffixProps: DropdownSuffixProps(
                    clearButtonProps: ClearButtonProps(isVisible: true),
                  ),
                ),
              ),
            ],
          ),
```
