### ISSUE TITLE
`_defaultSelectedItemWidget` throws a `A RenderFlex overflowed` if the itemToString returns a too long of a value

### ISSUE THREAD

**Issue by dannejosefsson** [salim-lachdhaf/dropdown_search#724]
**Describe the bug**
The default `_defaultSelectedItemWidget` throws a `A RenderFlex overflowed` exception if the `_itemAsString` function returns a too long value.

**To Reproduce**
1. In Examples pick the `Dialog` option
2. In `Suggested examples`, in the second dropdown
3. Search for Raymond Powlowski V and pick that name
4. Reduce the window width wise to its minimum

**Expected behavior**
The name will be shortened and the overflow will be replaced with an ellipsis.

**Screenshots**
The overflow:
<img width="496" alt="Screenshot 2024-12-09 at 15 09 24" src="https://github.com/user-attachments/assets/a9a272d2-3424-4209-80cf-dc256a1f8ec8">
It works as expected if the `Text` is wrapped with a `Flexible` widget:
<img width="486" alt="Screenshot 2024-12-09 at 15 08 54" src="https://github.com/user-attachments/assets/1e64db3e-aec8-4e2f-9ead-3204e7f06757">

**Desktop (please complete the following information):**
 - OS: MacOS 15.1.1 (24B91)
 - Browser: chrome
 - Version 131.0.6778.86

**Comment by salim-lachdhaf** [comment]
Hi @dannejosefsson , could you check v7.0.0-pre, i remember that i fixed something in this context

**Comment by dannejosefsson** [comment]
Yeah, the issue is fixed in the dev branch (v7.0.0-pre). If you intend to do a 6.0.2 down the line, I can fix a pr for master. But if you plan to go directly to 7 I think we can just close this one.

**Comment by salim-lachdhaf** [comment]
Yes, i plan to go directly to v7, just the time to make sure that everything is fine
