### ISSUE TITLE
Not picking dark mode

### ISSUE THREAD

**Issue by erperejildo** [salim-lachdhaf/dropdown_search#726]
The dropdown displayed looks white with no readable text in it.

Testing `DropdownSearch`

**Comment by salim-lachdhaf** [comment]
Any reproducible example ?

**Comment by erperejildo** [comment]
> Any reproducible example ?

Just enable darkMode:
`darkTheme: ThemeData.dark(),`

![WhatsApp Image 2024-12-11 at 16 11 33_cc6fe015](https://github.com/user-attachments/assets/3be59bef-bdbb-4a13-8e56-729220ed8710)

**Comment by erperejildo** [comment]
also, following image above (just to not open a different issue), if I tap on the TextField outside called Name, the white area doesn't close; in fact, it opens fully, hiding the element behind.

**Comment by salim-lachdhaf** [comment]
yes, there is two bugs in fact.
one is related to selected popup, in `multiSelection `mode when you select `ModalBottomSheet `you get `BottomSheet `and not `ModalBottomSheet` popup.

the second issue is as you mentioned in dark mode, BottomSheet is force to be white.

these issues are corrected in `7.0.0-pre2`



> if I tap on the TextField outside called Name, the white area doesn't close; in fact, it opens fully, hiding the element behind.

this is a normal behavior of `BottomSheet` you can try it even without using the package. the only exception is that we move the bottomSheet on top of the softkeyboard to make searching possible.
