### ISSUE TITLE
how to programaically clear (DropdownSearch<userModel>.multiSelection) values

### ISSUE THREAD

**Issue by jephin7** [salim-lachdhaf/dropdown_search#729]
how to programaically clear (DropdownSearch<userModel>.multiSelection) values
example clearing dropdown selected values when clicking some other button other than the cross in dropdownsearch multiselection

**Comment by salim-lachdhaf** [comment]
you can do that using `GlobalKey`.

Follow this example here: https://github.com/salim-lachdhaf/dropdown_search/blob/a8d7b881945f56848183e51c012e59df9d29b62e/example/lib/adaptive/dialogs.dart#L180
